apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max
spec:
  limits:
  - max:
      memory: 2Gi
    min:
      memory: 1Gi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max
spec:
  limits:
  - max:
      cpu: "2000"
    min:
      cpu: "1000m"
    type: Container